### ISSUE TITLE
Website Inaccessible

### ISSUE THREAD

**Issue by aadityabhatia** [social-protocols/global-brain#3]
Unable to reach the deployed github page at https://social-protocols.org/global-brain/

**Comment by fdietze** [comment]
Thank you for letting us know. The site is now working again.

It hat to do with me renaming the `social-protocols/social-protocols.github.io` repo to get the `social-protocols.github.io` domain back for the `GlobalBrain.jl` repo. Unfortunately that was not a good idea, because it broke other repositories (this one) which relied on the github organization domain. Now we use our domain for all repos.
